# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Code Made In Denmark
tagline:          'A danish programmer who does web-development and other coding'
description:      'A danish programmer who does web-development and other coding'
url:              http://dasmikko.github.io
baseurl:          /

author:
  name:           'Mikkel Andersen'
  url:            https://twitter.com/dasmikko

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dasmikko
