# Setup
title:               rekNa's little corner
tagline:             'random tech stuff'
description:         'Welcome to my little corner of the internet! I will blog about random projects, from web/app development to keyboard stuff'
url:                 https://rekna.xyz
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              rekNa
  url:               https://twitter.com/dasmikko
  email:             dasmikko@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
