# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Code Made In Denmark
tagline:          'A danish programmer who does web-development and indie-game development'
description:      'A danish programmer who loves to do web and game developmemt'
url:              http://dasmikko.github.io
baseurl:          /

author:
  name:           'Mikkel Andersen'
  url:            https://twitter.com/dasmikko

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dasmikko
