# Setup
baseurl:             ''
remote_theme:        b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: false # false (default) or true

footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'


# About/contact
author:
  name:              rekNa
  url:               https://twitter.com/dasmikko
  email:             dasmikko@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
